# Stage 1: Build image
FROM node:20-alpine AS build

# Install PostgreSQL client to use pg_isready
RUN apk add --no-cache postgresql-client

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Copy and make the entrypoint executable
COPY entrypoint.sh .
RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh

# Expose the port that Nest.js will use (default 3001)
EXPOSE 3001

# Set the entrypoint and default command
ENTRYPOINT ["./entrypoint.sh"]
CMD ["start"]
