# Stage 1: Imagem de build
FROM node:22.19 AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código
COPY . .
RUN npm run db:migrate
RUN npm run prismna:generate

# Expõe a porta que o Nest.js usará (padrão 3001)
EXPOSE 3001
