# Stage 1: Imagem de build
FROM node:22.19 AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código
COPY . .

# Copia e torna o entrypoint executável
COPY entrypoint.sh .
#RUN chmod +x entrypoint.sh --alterado para lidar com possíveis problemas de fim de linha do Windows (CRLF WINOWS E LF LINUX)
RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh

# Expõe a porta que o Nest.js usará (padrão 3001)
EXPOSE 3001

# Define o entrypoint e o comando padrão
ENTRYPOINT ["./entrypoint.sh"]
CMD ["start"]
